### ISSUE TITLE
NameError 

### ISSUE THREAD

**Issue by vishakhshetty** [Meerkats1999/ML-Lab#1]
NameError                              
![Screenshot (163)](https://user-images.githubusercontent.com/57668627/101454276-b31e2500-3956-11eb-89f0-cb5900308a2f.png)
Traceback (most recent call last)
<ipython-input-35-3f5fee26510f> in <module>
----> 1 model = LinearRegression(df)

<ipython-input-34-6a3a53fc7e69> in __init__(self, df)
      3     self.x = np.array(df["X"])
      4     self.y = np.array(df["Y"])
----> 5     self.n = np.size(x)
      6 
      7  def train(self):

NameError: name 'x' is not defined

**Comment by Meerkats1999** [comment]
Solved

**Comment by vishakhshetty** [comment]
Yes. Thanks
